//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministratorSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class arrange_testgame_between_ordinaryuser_and_testpaper
    {
        public int OrdinaryUserID { get; set; }
        public int TestPaperID { get; set; }
        public byte State { get; set; }
        public int TypeOfWork { get; set; }
        public System.DateTime Time { get; set; }
        public string Location { get; set; }
        public Nullable<short> Grade { get; set; }
        public short PassMark { get; set; }
        public string Marker { get; set; }
        public string Info { get; set; }
    }
}
