//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministratorSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collect_question_between_ordinaryuser_and_composition
    {
        public long OrdinaryUserID { get; set; }
        public long QuestionID { get; set; }
        public Nullable<System.DateTime> TimeOfCollection { get; set; }
    }
}
