//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministratorSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class generate_testpaper_between_administrator_and_testpaper
    {
        public int AdministratorID { get; set; }
        public int TestPaperID { get; set; }
        public System.DateTime TimeOfGeneration { get; set; }
    }
}
