//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministratorSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<administrator> administrator { get; set; }
        public DbSet<ordinaryuser> ordinaryuser { get; set; }
        public DbSet<establish_questionbank_between_administrator_and_questionbank> establish_questionbank_between_administrator_and_questionbank { get; set; }
        public DbSet<generate_testpaper_between_administrator_and_testpaper> generate_testpaper_between_administrator_and_testpaper { get; set; }
        public DbSet<question> question { get; set; }
        public DbSet<questionbank> questionbank { get; set; }
        public DbSet<testpaper> testpaper { get; set; }
        public DbSet<typeofwork> typeofwork { get; set; }
        public DbSet<arrange_testgame_between_ordinaryuser_and_testpaper> arrange_testgame_between_ordinaryuser_and_testpaper { get; set; }
        public DbSet<collect_question_between_ordinaryuser_and_question> collect_question_between_ordinaryuser_and_question { get; set; }
        public DbSet<comment_between_administrator_and_ordinaryuser> comment_between_administrator_and_ordinaryuser { get; set; }
        public DbSet<establish_questionbank_between_organizationuser_and_questionbank> establish_questionbank_between_organizationuser_and_questionbank { get; set; }
        public DbSet<generate_testpaper_between_organizationuser_and_testpaper> generate_testpaper_between_organizationuser_and_testpaper { get; set; }
        public DbSet<notice_of_testgame_between_organizationuser_and_ordinaryuser> notice_of_testgame_between_organizationuser_and_ordinaryuser { get; set; }
        public DbSet<organization> organization { get; set; }
        public DbSet<organizationuser> organizationuser { get; set; }
        public DbSet<systemnotice_> systemnotice_ { get; set; }
    }
}
