//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministratorSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public question()
        {
            this.questionbank = new HashSet<questionbank>();
            this.testpaper = new HashSet<testpaper>();
            this.collect_question_between_ordinaryuser_and_question = new HashSet<collect_question_between_ordinaryuser_and_question>();
        }
    
        public int ID { get; set; }
        public string Content { get; set; }
        public string TrueOrFalse { get; set; }
        public string Completion { get; set; }
        public string SingleChoice { get; set; }
        public string MultipleChoice { get; set; }
        public string QuestionAndAnswer { get; set; }
        public string Reading { get; set; }
        public string Essay { get; set; }
        public sbyte Score { get; set; }
        public string StandardAnswer { get; set; }
    
        public virtual ICollection<questionbank> questionbank { get; set; }
        public virtual ICollection<testpaper> testpaper { get; set; }
        public virtual ICollection<collect_question_between_ordinaryuser_and_question> collect_question_between_ordinaryuser_and_question { get; set; }
    }
}
