//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministratorSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemnotice_
    {
        public int AdministratorID { get; set; }
        public int OrganizationUserID { get; set; }
        public int OrdinaryUserID { get; set; }
        public System.DateTime TimeOfGeneration { get; set; }
        public string ContentOfNotice { get; set; }
    
        public virtual administrator administrator { get; set; }
        public virtual ordinaryuser ordinaryuser { get; set; }
        public virtual organizationuser organizationuser { get; set; }
    }
}
