//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministratorSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class testpaper
    {
        public long ID { get; set; }
        public string TestPaperName { get; set; }
        public short TestPaperScore { get; set; }
        public short TimeIntervalOfSavingAnswer { get; set; }
        public byte CanUseAgain { get; set; }
        public System.DateTime OverTime { get; set; }
        public int PassMark { get; set; }
        public sbyte Amount1 { get; set; }
        public byte Amount2 { get; set; }
        public byte Amount3 { get; set; }
        public byte Amount4 { get; set; }
        public byte Amount5 { get; set; }
        public byte Amount6 { get; set; }
    }
}
